import React from 'react';
import { Info } from 'lucide-react';

interface NonFictionDisclaimerProps {
  className?: string;
}

export const NonFictionDisclaimer: React.FC<NonFictionDisclaimerProps> = ({
  className = '',
}) => {
  return (
    <div
      className={`flex items-start gap-2.5 p-3 rounded-xl border border-amber-500/30 bg-amber-50/80 dark:bg-amber-950/20 text-amber-900 dark:text-amber-200 text-xs sm:text-sm ${className}`}
    >
      <Info className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
      <div>
        <span className="font-semibold text-amber-950 dark:text-amber-100">
          AI Disclaimer:{' '}
        </span>
        This content was generated by AI for language learning practice. Facts and details have not been independently verified.
      </div>
    </div>
  );
};

export default NonFictionDisclaimer;
