import React from 'react';
import { Info } from 'lucide-react';

interface NonFictionDisclaimerProps {
  className?: string;
}

export const NonFictionDisclaimer: React.FC<NonFictionDisclaimerProps> = ({
  className = '',
}) => {
  return (
    <div
      className={`flex items-center gap-1.5 text-slate-400 dark:text-slate-500 text-[11px] sm:text-xs w-full ${className}`}
    >
      <Info className="w-3.5 h-3.5 text-slate-400 dark:text-slate-500 shrink-0" />
      <div>
        <span className="font-medium text-slate-500 dark:text-slate-400">
          AI Disclaimer:{' '}
        </span>
        This content was generated by AI for language learning practice. Facts and details have not been independently verified.
      </div>
    </div>
  );
};

export default NonFictionDisclaimer;
