import { Info } from 'lucide-react';
import type React from 'react';

interface NonFictionDisclaimerProps {
  className?: string;
}

export const NonFictionDisclaimer: React.FC<NonFictionDisclaimerProps> = ({
  className = '',
}) => {
  return (
    <div
      className={`flex items-center gap-1.5 text-slate-400 dark:text-slate-500 text-[11px] sm:text-xs w-full ${className}`}
    >
      <Info className="w-3.5 h-3.5 text-slate-400 dark:text-slate-500 shrink-0" />
      <div>
        <span className="font-medium text-slate-500 dark:text-slate-400">
          AI Disclaimer:{' '}
        </span>
        Generated by AI for language learning and reading practice. Facts and
        details have not been independently verified. Not intended as medical,
        legal, financial, or safety advice. Fictional characters, names, and
        situations do not depict or represent real living persons.
      </div>
    </div>
  );
};

export default NonFictionDisclaimer;
