import { FileSignature, Info, Layers } from 'lucide-react';
import type React from 'react';
import { GENRES, WRITING_TYPE_GENRES } from '../../types';
import { WRITING_TYPES } from './storyConfigConstants';

interface GenreSelectorProps {
  writingType: string;
  onWritingTypeChange: (type: string) => void;
  genre: string;
  onGenreChange: (genre: string) => void;
}

export default function GenreSelector({
  writingType,
  onWritingTypeChange,
  genre,
  onGenreChange,
}: GenreSelectorProps) {
  const handleWritingTypeClick = (typeId: string) => {
    onWritingTypeChange(typeId);
    const available = WRITING_TYPE_GENRES[typeId];
    if (available && available.length > 0) {
      if (!available.some((g) => g.id === genre)) {
        onGenreChange(available[0].id);
      }
    }
  };

  return (
    <>
      {/* Writing Style / Type (Selected First) */}
      <div className="space-y-3">
        <label className="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
          <FileSignature className="w-4 h-4 text-tj-primary" />
          Writing Style / Type
        </label>
        <div className="grid grid-cols-2 gap-3">
          {WRITING_TYPES.map((wt) => {
            const isSelected = writingType === wt.id;
            return (
              <button
                key={wt.id}
                type="button"
                onClick={() => handleWritingTypeClick(wt.id)}
                className={`p-3.5 border rounded-xl text-left transition-all duration-200 flex flex-col items-start gap-1 cursor-pointer bg-tj-bg-card hover:border-tj-primary ${
                  isSelected
                    ? 'border-tj-primary bg-tj-primary-light dark:bg-tj-primary-light/10 text-tj-primary dark:text-tj-primary-hover ring-2 ring-tj-primary/20'
                    : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 bg-transparent text-slate-700 dark:text-slate-300'
                }`}
              >
                <span className="text-xs font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5">
                  <span>{wt.emoji}</span> {wt.label}
                </span>
                <p className="text-[10px] text-slate-600 dark:text-slate-300 leading-snug mt-0.5 font-sans">
                  {wt.desc}
                </p>
              </button>
            );
          })}
        </div>
      </div>

      {/* Genre / Theme (Filtered by Writing Type) */}
      <div className="space-y-3">
        <label className="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
          <Layers className="w-4 h-4 text-tj-primary" />
          {writingType === 'expository' || writingType === 'analytical'
            ? 'Topic / Focus Area'
            : 'Genre / Theme'}
        </label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {(WRITING_TYPE_GENRES[writingType] || GENRES).map((g) => {
            const isSelected = genre === g.id;
            const emojiMatch = g.label.match(
              /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F000}-\u{1F9FF}]/u,
            );
            const emoji = emojiMatch ? emojiMatch[0] : '';
            const text = g.label.replace(emoji, '').trim();
            return (
              <button
                key={g.id}
                type="button"
                onClick={() => onGenreChange(g.id)}
                className={`flex flex-col items-center justify-center p-3 rounded-xl border text-center transition-all cursor-pointer ${
                  isSelected
                    ? 'border-tj-primary bg-tj-primary-light dark:bg-tj-primary-light/10 text-tj-primary dark:text-tj-primary-hover ring-2 ring-tj-primary/20'
                    : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 bg-transparent text-slate-700 dark:text-slate-300'
                }`}
              >
                <span className="text-2xl mb-1">{emoji}</span>
                <span className="text-xs font-semibold">{text}</span>
              </button>
            );
          })}
        </div>
        {(genre === 'nonfiction' || writingType === 'expository') && (
          <div className="mt-2.5 p-3 bg-amber-50 dark:bg-amber-950/20 text-amber-700 dark:text-amber-400 text-xs rounded-xl border border-amber-100 dark:border-amber-950/30 flex items-start gap-2 animate-fade-in">
            <Info className="w-4 h-4 shrink-0 mt-0.5 text-amber-500 dark:text-amber-400" />
            <span>
              <strong>Hallucination Warning:</strong> Factual and informational
              topics generated by AI may contain inaccuracies or
              hallucinations, especially when simplified for language learning.
            </span>
          </div>
        )}
      </div>
    </>
  );
}
