/**
 * Story generation cost and word-count estimation helpers.
 * Extracted from StoryConfigForm.tsx.
 *
 * With the move to full-context batch generation (5 chapters per call),
 * hybrid summarisation is no longer used. Every chapter call receives the
 * complete story history as input, so costs grow progressively with each batch.
 */

import { GEMINI_MODELS } from '../constants/models';

/** Returns the recommended chapter word count for a CEFR level. */
export const getRecommendedWordCount = (level: string): number => {
  switch (level) {
    case 'A1':
      return 150;
    case 'A2':
      return 250;
    case 'B1':
      return 350;
    case 'B2':
      return 450;
    case 'C1':
    case 'C2':
      return 500;
    default:
      return 300;
  }
};

export interface UsageEstimate {
  totalWords: number;
  totalTokens: number;
  totalCost: number;
}

/**
 * Estimates token consumption and API cost for a full story generation.
 *
 * Assumes full-context input growth: each chapter receives all previous
 * chapters as plain text (no hybrid summarisation). Batch calls (5 chapters
 * per API call) share a single input context, reducing the total number of
 * API round-trips while the input cost grows linearly with the story length.
 */
export const calculateEstimatedUsage = (
  chapters: number,
  wordCount: number,
  modelId: string,
): UsageEstimate => {
  const tokenPerWord = 1.33;
  // Static overhead per batch call: system prompt + outline + guidance ≈ 1,500 tokens
  const staticInputTokensPerBatch = 1500;
  // Static JSON scaffolding output overhead per chapter
  const staticOutputTokensPerChapter = 100;

  // Find model matching modelId robustly (exact match first, then fuzzy contains match)
  let model = GEMINI_MODELS.find((m) => m.id === modelId);
  if (!model && modelId) {
    const cleanId = modelId.toLowerCase().replace(/[^a-z0-9]/g, '');
    model = GEMINI_MODELS.find((m) => {
      const cleanMId = m.id.toLowerCase().replace(/[^a-z0-9]/g, '');
      return cleanMId.includes(cleanId) || cleanId.includes(cleanMId);
    });
  }
  // Default to DeepSeek V4 Flash instead of a free model if not found
  if (!model) {
    model =
      GEMINI_MODELS.find((m) => m.id === 'deepseek/deepseek-v4-flash') ||
      GEMINI_MODELS[0];
  }

  // Detect reasoning/thinking models to budget for internal chain-of-thought tokens
  const isReasoningModel =
    model.supportsThinkingLevel ||
    model.id.includes('reasoner') ||
    model.id.includes('pro') ||
    model.id.includes('r1');

  // Outline generation overhead (more output tokens are generated by reasoning models)
  const outlineInputTokens = 1500;
  const outlineOutputTokens = isReasoningModel ? 3000 : 1500;

  // Additional reasoning overhead per chapter for reasoning models
  const reasoningChapterOutputOverhead = isReasoningModel ? 1500 : 0;

  const BATCH_SIZE = 5;
  const batchCount = Math.ceil(chapters / BATCH_SIZE);

  let totalInputTokens = outlineInputTokens;
  let totalOutputTokens = outlineOutputTokens;

  for (let batch = 0; batch < batchCount; batch++) {
    const firstChapterInBatch = batch * BATCH_SIZE + 1;
    const chaptersAlreadyWritten = firstChapterInBatch - 1;
    const wordsAlreadyWritten = chaptersAlreadyWritten * wordCount;

    // Full context: all previous chapters sent as plain text
    const prevContextTokens = Math.round(wordsAlreadyWritten * tokenPerWord);

    const chaptersInThisBatch = Math.min(
      BATCH_SIZE,
      chapters - chaptersAlreadyWritten,
    );

    // Input: static overhead + full story history
    totalInputTokens += staticInputTokensPerBatch + prevContextTokens;

    // Output: all chapter content in this batch + reasoning overhead per chapter
    totalOutputTokens +=
      chaptersInThisBatch *
      (staticOutputTokensPerChapter +
        Math.round(wordCount * tokenPerWord) +
        reasoningChapterOutputOverhead);
  }

  const inputCost = (totalInputTokens / 1_000_000) * model.inputCost1M;
  const outputCost = (totalOutputTokens / 1_000_000) * model.outputCost1M;

  return {
    totalWords: chapters * wordCount,
    totalTokens: totalInputTokens + totalOutputTokens,
    totalCost: inputCost + outputCost,
  };
};
